export const FETCH_SINGLE_STORY = "FETCH_SINGLE_STORY";
export const MUTATE_SINGLE_STORY = "MUTATE_SINGLE_STORY";
export const GET_SINGLE_STORY = "GET_SINGLE_STORY";
export const INIT_SINGLE_STORY = "INIT_SINGLE_STORY";
export const FETCH_SINGLE_STORY_COVERPHOTO = "FETCH_SINGLE_STORY_COVERPHOTO";
